### ISSUE TITLE
WebExtensions?

### ISSUE THREAD

**Issue by brettz9** [mdn/browser-api-demo#2]
Hi,

Having such a browser element is I think very exciting and with much underestimated potential.

Is there any means of enabling this in WebExtensions, and if not, could there be?

----
On a somewhat tangential note, in case you might be the right person(s) to talk to, I'm also very interested in seeing such browser elements accessible (though with security concerns addressed) in regular web scripts for the purposes of allowing each iframe on a page to have its own independently navigable, cross-domain browser history (albeit not accessible to scripting), with the intent of facilitating side-by-side display of commentary, especially useful in an unfolding age of expanding screens (or projectors) as well as gesture controlled devices that can take advantage of the larger screen size.

In this manner, one might show wiki pages hosting resources relevant to a particular book verse, legal text, etc., which could be browsed without losing the view on the text under discussion and without losing sight of the other commentary resource pages:  https://bugzilla.mozilla.org/show_bug.cgi?id=618354

Brett

**Comment by Happy-Ferret** [comment]
FYI,

there are some talks about it over at Bugzilla.

https://bugzilla.mozilla.org/show_bug.cgi?id=1318532
